johnlimadev/force-app/main/default/objects/Corretora__c/Corretora__c.object-meta.xml
<CustomObject>
    <label>Corretora</label>
    <nameField>
        <label>Corretora Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Corretoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

johnlimadev/force-app/main/default/objects/Corretora__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

johnlimadev/force-app/main/default/objects/Lead/recordTypes/A.recordType-meta.xml
<RecordType>
    <fullName>A</fullName>
    <active>true</active>
    <businessProcess>A</businessProcess>
    <description>A</description>
    <label>A</label>
</RecordType>

johnlimadev/force-app/main/default/objects/Opportunity/fields/Corretora__c.field-meta.xml
<CustomField>
    <fullName>Corretora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretora</label>
    <referenceTo>Corretora__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

johnlimadev/force-app/main/default/classes/TriggerHandlerLead.cls
public with sharing class TriggerHandlerLead {
    public TriggerHandlerLead() {

    }

    public void testingIsExecutingFromTrigger() {
        System.debug(Trigger.isExecuting);
    }

    public void manageConvertedLeads() {
            List<Lead> convertedLeads = new List<Lead>();
            // Id idRecordTypePME =    Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PME').getRecordTypeId();
            Id idRecordTypePME =    Schema.SObjectType.Lead.getRecordTypeInfosByName().get('A').getRecordTypeId();
            List<Id> idDasPropostasRelacionadas = new List<Id>();

            for (Lead l : (List<Lead>) Trigger.new) {
                if (l.RecordTypeId == idRecordTypePME && l.isConverted == TRUE && l.ConvertedOpportunityId != NULL) {
                    convertedLeads.add(l);
                    idDasPropostasRelacionadas.add(l.ConvertedOpportunityId);
                }
            }

            if (convertedLeads == NULL || convertedLeads.isEmpty()) return;
            Corretora__c corretoraDefault = null;
            try {
                corretoraDefault = [SELECT Id FROM Corretora__c WHERE cnpj__c = '123456' /* Corretora_Default__c = TRUE */];
            } catch (Exception e) {
                System.debug('Não há uma corretora Default');
                return;
            }

            List<Opportunity> propostas = [SELECT Id, Name, Corretora__c FROM Opportunity WHERE Id IN: idDasPropostasRelacionadas];
            for (Opportunity proposta : propostas)
                proposta.Corretora__c = corretoraDefault.Id;
            
            update propostas;
            


    }
}