johnlimadev/force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>Msg-{0000}</displayFormat>
        <label>Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

johnlimadev/force-app/main/default/objects/Message__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

johnlimadev/force-app/main/default/objects/Message__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Not Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

johnlimadev/force-app/main/default/classes/FlowHelper.cls
public class FlowHelper {
    @InvocableMethod(label = 'Get Messages' description = 'Get all Messages of a specific Case with an Apex defined criteria')
    public static List<List<Message__c>> getMessages(List<String> caseIds) {
        String CancelOptions;
        List<List<Message__c>> returnList = new List<List<Message__c>>(); 
        List<Message__c> messages = new List<Message__c>();
        try {
            messages = [SELECT Id, Name, Case__c, Stage__c FROM Message__c WHERE Case__c IN: caseIds];
            returnList.add(messages);
        } Catch(Exception e) {
            System.debug('Error Canceloptions current user: ' + e.getMessage());
        }
        return returnList;
    }
}